### ISSUE TITLE
shiny presentation renders empty black screen

### ISSUE THREAD

**Issue by nicolasgaraycoa** [rstudio/rmarkdown#2514]
Hi. I ran the default template for a Shiny Presentation and it rendered an empty, black screen with no errors. All of my packages are updated and I'm running the latest versions of RStudio Desktop and R. I've attached the code I ran and the versions I'm using in two separate text files.  I appreciate your help in advance. 

[r_version.txt](https://github.com/rstudio/rmarkdown/files/12577726/r_version.txt)
[demo_template.txt](https://github.com/rstudio/rmarkdown/files/12577772/demo_template.txt)

**Comment by cderv** [comment]
Thanks for the report. I can reproduce too on my side. 

Error in browser console is 
````
Uncaught TypeError: Cannot read properties of null (reading 'querySelectorAll')
    at SlideDeck.onDomLoaded_ (slide-deck.js:68:32)
    at new SlideDeck (slide-deck.js:23:31)
    at complete (slide-deck.js:791:26)
    at c (modernizr.custom.45394.js:4:11368)
    at i (modernizr.custom.45394.js:4:11444)
    at B (modernizr.custom.45394.js:4:11634)
    at Modernizr.load (modernizr.custom.45394.js:4:12552)
    at loadDeck (slide-deck.js:789:13)
    at slide-deck.js:801:5
````

**Comment by cderv** [comment]
Ok I believe this is a breakage with latest shiny version. It is not in your session information, but I suppose you are using 1.7.5. 

Installing previous version works as expected. You can try installing old version using 
* `pak::pak("cran/shiny@1.7.4.1")`
* `renv::install("shiny@1.7.4.1")`
* `devtools::install_version("shiny", "1.7.4.1")`

depending on the tool you use 

We now need to find what the issue is to see if we need to adapt, or if this is a breakage in shiny part.

**Comment by cderv** [comment]
This is the commit that cause the issue from a git bisect: https://github.com/rstudio/shiny/commit/a06354040717de6a29644461bd6ed4665816f734

It is the build a the new `shiny.js` version as part of 
* https://github.com/rstudio/shiny/pull/3666

Change is in NEWS as the following
> Closed https://github.com/rstudio/shiny/issues/789: Dynamic UI is now rendered asynchronously, thanks in part to the newly exported Shiny.renderDependenciesAsync(), Shiny.renderHtmlAsync(), and Shiny.renderContentAsync(). Importantly, this means <script> tags are now loaded asynchronously (the old way used XMLHttpRequest, which is synchronous). In addition, Shiny now manages a queue of async tasks (exposed via Shiny.shinyapp.taskQueue) so that order of execution is preserved. (https://github.com/rstudio/shiny/pull/3666)

@wch @schloerke I would love a quick explanation on the change, probably quick teaching about this async impact and how it could conflict with ioslides. 

Thank you

**Comment by cderv** [comment]
BTW the error in console is from 
https://github.com/rstudio/rmarkdown/blob/599dc0bd7a08422bbe7138e21175007b33a9b965/inst/rmd/ioslides/ioslides-13.5.1/js/slide-deck.js#L68

because `this.container` is `null`. So probably something not initialized anymore as it should

**Comment by gadenbuie** [comment]
Thanks for the detailed detective work @cderv! The primary change that Shiny made was that dynamically created content is now rendered asynchronously in the browser. This change from synchronous to async has created ripples of subtle timing issues in several places.

In this case, I'm pretty sure the issue stems from the fact that rmarkdown uses a dynamic `uiOutput()` to render the document to the app.

https://github.com/rstudio/rmarkdown/blob/599dc0bd7a08422bbe7138e21175007b33a9b965/R/shiny.R#L368

What's happening is that ioslides is waiting for the `DOMContentLoaded` browser event and then initializing the slides. But dynamic UI content is now rendered asynchronously by Shiny in the browser, meaning that the `<slides>` content isn't on the page yet when the `DOMContentLoaded` event is fired.

In #2516, I proposed adding Shiny-specific initialization that is guaranteed to happen _after_ `<slides>` are available.

**Comment by cderv** [comment]
Thanks @gadenbuie ! 

Now that you explain it, I understand better this async change I saw in the release note. 

**rmarkdown** using `shiny::uiOutput` to create an interactive document, this type of issue can happen with other dependencies that could be used ?

**Comment by cderv** [comment]
This should be fixed in dev version now.
