### ISSUE TITLE
import matplotlib.pyplot as plt error??

### ISSUE THREAD

**Issue by joebling** [rstudio/rmarkdown#837]
```
running: /usr/bin/python2  -c 'import matplotlib.pyplot as plt'
Quitting from lines 13-14 (py_test.rmd) 
Error in engine(options) : Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from matplotlib.externals.six.moves import tkinter as Tk
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/externals/six.py", line 199, in load_module
    mod = mod._resolve()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/externals/six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/externals/six.py", line 80, in _import_module
    __import__(name)
  File "/usr/lib/python2.7/lib-tk/Tkinter.p
此外: Warning message:
运行命令''/usr/bin/python2'  -c 'import matplotlib.pyplot as plt' 2>&1'的状态是1 
```

**Comment by yihui** [comment]
Not sure  about the reason for this error, since I don't know much about Python, and I don't see the actual error message above. Could you run the command in your terminal and see what it returns?

```bash
/usr/bin/python2  -c 'import matplotlib.pyplot as plt'
```

**Comment by yihui** [comment]
I believe this issue will eventually be solved by https://github.com/rstudio/reticulate/pull/107.
